name: Build and deploy Pygbag

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le jeu
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer Pygbag
        run: python -m pip install --upgrade pygbag

      - name: Construire le jeu web
        run: python -m pygbag --build --disable-sound-format-error .

      - name: Publier sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
